app_django/app_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

app_django/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("all/", views.AllView.as_view(), name="all"),
    path("logout/", views.logout_view, name="logout"),

    path("login/", views.LoginV.as_view(), name="login"),

    path("statistics/", views.statisitcs, name="statistics"),
    path("question/", views.question, name="question"),

    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/frequency", views.FreqView.as_view(), name="frequency"),

    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

app_django/polls/models.py
import datetime
from typing import List

from django.db import models
from django.utils import timezone


# Create your models here.
class Choice:
    pass


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def get_choices(self) -> List[Choice]:
        return Choice.objects.filter(question_id=self.id)

    def age(self) -> datetime.datetime:
        return timezone.now() - self.pub_date

    def __str__(self):
        return self.question_text

    def sum_votes(self) -> int:
        return sum(map(lambda v: v.votes, self.get_choices()))

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1) and self.pub_date <= timezone.now()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def perc(self) -> int:
        if self.votes == 0:
            return 0
        return int((self.votes/self.question.sum_votes())*100)

    def __str__(self):
        return self.choice_text

app_django/polls/forms.py
from django import forms


class QuestionForm(forms.Form):
    question = forms.CharField(label="Question", max_length=100,required=True)
    reponse0 = forms.CharField(label="Réponse", max_length=100,required=True)
    reponse1 = forms.CharField(label="Réponse", max_length=100,required=False)
    reponse2 = forms.CharField(label="Réponse", max_length=100,required=False)

app_django/polls/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import QuestionForm
from .models import Question, Choice


# Create your views here.


def statisitcs(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"sondages": Question.objects.count(),"choix" : Choice.objects.count()}
    return render(request, "polls/statistics.html", context)

def question(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        if not request.user.is_authenticated:
            raise PermissionDenied()
        # create a form instance and populate it with data from the request:
        form = QuestionForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:

            qs = Question(None,form.cleaned_data.get("question"),timezone.now())

            qs.save()

            i = 0

            while "reponse" + str(i) in form.cleaned_data:
                rep = form.cleaned_data.get("reponse"+str(i))
                if rep.strip() == "":
                    break
                Choice(None,qs.id,rep,0).save()
                i+= 1


            return HttpResponseRedirect("/polls/")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = QuestionForm()

    return render(request, "polls/question.html", {"form": form})

class FreqView(generic.DetailView):
    template_name = "polls/frequency.html"
    model = Question

class LoginV(LoginView):
    template_name = "polls/login.html"
    next_page = "/polls/"


class AllView(generic.ListView):
    template_name = "polls/all.html"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")



class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("polls:index"))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

app_django/polls/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}Polls{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/polls">Home</a></li>
            <li><a href="/polls/all">All</a></li>
            {% if user.is_authenticated  %}
                <li>{{ user.username }}</li>
                <li><a href="/polls/logout">Logout</a></li>
            {% else %}
                <li><a href="/polls/login">Login</a></li>
            {% endif %}
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app_django/polls/templates/polls/all.html
{% extends "main.html" %}


{% block content %}

{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'polls:frequency' question.id %}">{{ question.id }} {{ question.question_text }} - {{ question.pub_date }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

app_django/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

</body>
</html>

app_django/polls/templates/polls/frequency.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Frequency</title>
</head>
<body>
    <ul>
    {% for choice in question.get_choices %}
        <li><a>{{ choice.choice_text }} - {{choice.perc }} % {{ choice.votes }}</a></li>
    {% endfor %}
    </ul>

</body>
</html>

app_django/polls/templates/polls/index.html
{% extends "main.html" %}


{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }} - {{ question.pub_date }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

app_django/polls/templates/polls/login.html
{% extends "main.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'polls:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<input type="submit">
<input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

app_django/polls/templates/polls/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Question</title>
</head>
<body>

<form action="{% url 'polls:question' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

</body>
</html>

app_django/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>

app_django/polls/templates/polls/statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pools</title>
</head>
<body>

<h2>Statistics</h2>

{{ sondages }} sondages

<br/>

{{ choix }} choix possibles

{{ votes }} votes

{{ pss }} possibilités en moyenne



</body>
</html>